AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true

Metrics/BlockLength:
  Exclude:
    - spec/lib/**/*.rb

Metrics/LineLength:
  Exclude:
    - Gemfile

Bundler/DuplicatedGem:
  Exclude:
    - Gemfile

Bundler/OrderedGems:
  Exclude:
    - Gemfile
